http:
    listenHost: 0.0.0.0
    listenPort: 8000

keys:
    brokerConnect: 1
    brokerMessage: 2
    handlerAccept: 1
    handlerReject: 2

rabbitMq:
  enabled: false
  server: localhost
  port: 5672
  vhost: /
  user: guest
  password: guest
  exchange: Altis.AlertHandler
