http:
    host: 0.0.0.0
    port: 443

security:
  authentication:
    enabled: true
    method: digest
  ssl:
    passphrase: dummypassphrase
    enabled: true
  twilio:
    validate: true
    authToken: dummyauthtoken

keys:
    brokerConnect: 1
    brokerMessage: 2
    handlerAccept: 1
    handlerReject: 2

company:
    name: 'TestCompany'
    
rabbitMq:
  enabled: false
  server: localhost
  port: 5672
  vhost: /
  user: guest
  password: guest
  exchange: DummyExchange
  connectionRetryInterval: 1000

# log4net equivalent log levels can be debug, info, warn, error (no fatal in winston)
logger:
  file:
    enabled: false
    path: C:\Temp\twilio-adapter.log
    level: debug
  console:
    enabled: true
    level: debug
