http:
    listenHost: 0.0.0.0
    listenPort: 8000

keys:
    brokerConnect: 1
    brokerMessage: 2
    handlerAccept: 1
    handlerReject: 2

company:
    name: 'TestCompany'
    
rabbitMq:
  enabled: true
  server: localhost
  port: 5672
  vhost: /
  user: guest
  password: guest
  exchange: DummyExchange
  connectionRetryInterval: 1000

# log4net equivalent log levels can be debug, info, warn, error (no fatal in winston)
logger:
  file:
    enabled: true
    path: C:\Temp\twilio-adapter.log
    level: debug
  console:
    enabled: true
    level: debug
